import { defineField, defineType } from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'general', title: 'General', default: true },
    { name: 'homepage', title: 'Homepage' },
    { name: 'about', title: 'About & shop' },
    { name: 'legal', title: 'Legal pages' },
  ],
  fields: [
    defineField({ name: 'brandName', title: 'Brand name', type: 'string', group: 'general', initialValue: 'AYRO' }),
    defineField({ name: 'contactEmail', title: 'Contact email', type: 'string', group: 'general' }),
    defineField({ name: 'logo', title: 'Logo', type: 'image', group: 'general' }),
    defineField({ name: 'logoAlt', title: 'Logo alt text', type: 'string', group: 'general' }),
    defineField({ name: 'heroEyebrow', title: 'Hero eyebrow', type: 'string', group: 'homepage' }),
    defineField({ name: 'heroHeadline', title: 'Hero headline', description: 'Use | to split lines, e.g. Wear your|ambition.', type: 'string', group: 'homepage' }),
    defineField({ name: 'heroSubcopy', title: 'Hero subcopy', type: 'text', rows: 2, group: 'homepage' }),
    defineField({ name: 'heroImage', title: 'Hero image', type: 'image', group: 'homepage' }),
    defineField({ name: 'heroImageAlt', title: 'Hero image alt', type: 'string', group: 'homepage' }),
    defineField({ name: 'promoText', title: 'Promo bar text', type: 'string', group: 'homepage' }),
    defineField({ name: 'storyTitle', title: 'Story title', type: 'string', group: 'about' }),
    defineField({ name: 'storyBody', title: 'Story body', type: 'text', rows: 4, group: 'about' }),
    defineField({ name: 'storyImage', title: 'Story image', type: 'image', group: 'about' }),
    defineField({ name: 'storyImageAlt', title: 'Story image alt', type: 'string', group: 'about' }),
    defineField({ name: 'shippingNote', title: 'Shipping note', type: 'string', group: 'about' }),
    defineField({ name: 'shopTitle', title: 'Shop page title', type: 'string', group: 'about' }),
    defineField({ name: 'shopSubtitle', title: 'Shop page subtitle', type: 'text', rows: 2, group: 'about' }),
    defineField({
      name: 'socials',
      title: 'Social links',
      type: 'array',
      group: 'about',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'label', type: 'string', title: 'Label' },
            { name: 'handle', type: 'string', title: 'Handle' },
            { name: 'url', type: 'url', title: 'URL' },
          ],
        },
      ],
    }),
    defineField({ name: 'categoryEssentials', title: 'Category tile — Essentials', type: 'image', group: 'homepage' }),
    defineField({ name: 'categoryGraphics', title: 'Category tile — Graphics', type: 'image', group: 'homepage' }),
    defineField({ name: 'categoryLimited', title: 'Category tile — Limited', type: 'image', group: 'homepage' }),
    defineField({
      name: 'privacyIntro',
      title: 'Privacy Policy — intro',
      type: 'text',
      rows: 3,
      group: 'legal',
      description: 'Opening paragraph. Use {{brandName}} for the brand name.',
    }),
    defineField({
      name: 'privacySections',
      title: 'Privacy Policy — sections',
      type: 'array',
      group: 'legal',
      of: [{ type: 'legalSection' }],
    }),
    defineField({
      name: 'privacyLastUpdated',
      title: 'Privacy Policy — last updated',
      type: 'string',
      group: 'legal',
      initialValue: 'June 2026',
    }),
    defineField({
      name: 'returnsIntro',
      title: 'Returns & Refunds — intro',
      type: 'text',
      rows: 3,
      group: 'legal',
      description: 'Opening paragraph. Use {{brandName}} for the brand name.',
    }),
    defineField({
      name: 'returnsSections',
      title: 'Returns & Refunds — sections',
      type: 'array',
      group: 'legal',
      of: [{ type: 'legalSection' }],
    }),
    defineField({
      name: 'returnsLastUpdated',
      title: 'Returns & Refunds — last updated',
      type: 'string',
      group: 'legal',
      initialValue: 'June 2026',
    }),
  ],
})
